const API=(window.SLE_CONFIG?.API_URL||'').replace(/\/$/,'');
const app=document.getElementById('app');
const state={token:localStorage.getItem('sle_token')||'',me:null,audits:[],questions:[],audit:null,screen:'home',visit:0,step:0};
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;setTimeout(()=>t.hidden=true,3200)}
function authHeaders(){return state.token?{'Authorization':`Bearer ${state.token}`}:{}}
async function api(path,opt={}){
  const res=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...authHeaders(),...(opt.headers||{})}});
  let data={};
  try{data=await res.json()}catch{}
  if(!res.ok){
    let message=`Ошибка ${res.status}`;
    if(typeof data.detail==='string') message=data.detail;
    else if(Array.isArray(data.detail)) message=data.detail.map(x=>`${(x.loc||[]).slice(1).join('.')||'поле'}: ${x.msg}`).join('; ');
    else if(data.detail?.message) message=data.detail.message;
    else if(data.message) message=data.message;
    console.error('API error',path,data);
    throw new Error(message);
  }
  return data;
}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(content){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><i></i>SLE</div><div>${state.me?`${esc(state.me.full_name)} <button class="pill" id="logout">Выйти</button>`:''}</div></header><div class="container">${content}</div></div>`;$('#logout')?.addEventListener('click',logout)}
function logout(){localStorage.removeItem('sle_token');state.token='';state.me=null;renderLogin()}
async function boot(){window.addEventListener('online',syncStatus);window.addEventListener('offline',syncStatus);syncStatus();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(!state.token)return renderLogin();try{state.me=await api('/auth/me');await home()}catch(e){logout()}}
function syncStatus(){$('#offline')?.toggleAttribute('hidden',navigator.onLine)}
function renderLogin(){app.innerHTML=`<div class="login"><div class="login-logo">SLE</div><div class="card accent"><h1>Вход</h1><p class="muted">Введите логин и пароль</p><form id="login"><div class="field"><label>Логин</label><input name="login" required autocomplete="username"></div><div class="field" style="margin-top:12px"><label>Пароль</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn primary full" style="margin-top:16px">Войти</button></form></div></div>`;$('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});state.token=d.access_token;localStorage.setItem('sle_token',state.token);state.me=await api('/auth/me');home()}catch(err){toast(err.message)}}}
async function home(){try{state.audits=await api('/audits')}catch(e){toast(e.message)}const draft=state.audits.find(a=>['draft','in_progress'].includes(a.status) && a.is_mine!==false);let admin='';if(['admin','manager'].includes(state.me.role))admin=`<button class="pill" data-page="admin">Управление</button>`;shell(`<div class="nav"><button class="pill active" data-page="home">Главная</button><button class="pill" data-page="history">История</button>${admin}</div>${draft?`<div class="card accent"><h2>Незавершённый аудит</h2><p>${esc(draft.employee_name)} · ${esc(draft.region_name)}</p><p class="muted">Визит ${Math.max(1,draft.current_visit)} из 5 · шаг ${Math.max(1,draft.current_step)} из 7</p><button class="btn primary" data-resume="${draft.id}">Продолжить</button></div>`:''}<div class="card"><h2>Новый аудит</h2><p class="muted">Оценка сотрудника по пяти торговым точкам</p><button class="btn primary" id="newAudit" ${draft?'disabled':''}>Начать</button></div><div class="card"><h2>Последние аудиты</h2>${auditTable(state.audits.slice(0,8))}</div>`);bindNav();$('#newAudit')?.addEventListener('click',newAuditForm);$$('[data-resume]').forEach(b=>b.onclick=()=>openAudit(b.dataset.resume))}
function auditTable(rows){if(!rows.length)return'<p class="muted">Аудитов пока нет</p>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Сотрудник</th><th>Статус</th><th>Результат</th></tr></thead><tbody>${rows.map(a=>`<tr data-open="${a.id}" style="cursor:pointer"><td>${esc(a.audit_date)}</td><td>${esc(a.employee_name)}</td><td><span class="badge ${a.status==='completed'?'ok':'warn'}">${statusName(a.status)}</span></td><td>${a.total_percent==null?'—':a.total_percent+'%'}</td></tr>`).join('')}</tbody></table></div>`}
function statusName(s){return({draft:'Черновик',in_progress:'В процессе',completed:'Завершён',cancelled:'Отменён'})[s]||s}
function bindNav(){$$('[data-page]').forEach(b=>b.onclick=()=>{if(b.dataset.page==='home')home();if(b.dataset.page==='history')history();if(b.dataset.page==='admin')adminPage()});$$('[data-open]').forEach(r=>r.onclick=()=>openAudit(r.dataset.open))}
async function history(){state.audits=await api('/audits');shell(`<div class="nav"><button class="pill" data-page="home">Главная</button><button class="pill active">История</button></div><div class="card"><h1>История аудитов</h1>${auditTable(state.audits)}</div>`);bindNav()}
async function newAuditForm(){
  let regions=[];
  try{regions=await api('/audits/regions')}catch(e){return toast(e.message)}
  const fixed=state.me.role==='leader';
  if(fixed && regions.length!==1) return toast('Для руководителя должен быть назначен один регион');
  let employees=[];
  if(fixed) employees=await api('/audits/employees?region_id='+regions[0].id);
  shell(`<div class="card accent"><h1>Новый аудит</h1><form id="createAudit"><div class="grid two"><div class="field"><label>Дата</label><input type="date" name="audit_date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Регион</label>${fixed?`<input value="${esc(regions[0].name)}" disabled><input type="hidden" name="region_id" value="${regions[0].id}">`:`<select name="region_id" id="region" required><option value="">Выберите регион</option>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select>`}</div><div class="field" style="grid-column:1/-1"><label>Сотрудник</label><select name="employee_id" id="employee" required><option value="">Выберите сотрудника</option>${employees.map(x=>`<option value="${x.id}">${esc(x.full_name)}</option>`).join('')}</select></div></div><div class="actions" style="margin-top:16px"><button type="button" class="btn secondary" id="back">Назад</button><button class="btn primary">Создать аудит</button></div></form></div>`);
  $('#back').onclick=home;
  $('#region')?.addEventListener('change',async e=>{const list=e.target.value?await api('/audits/employees?region_id='+e.target.value):[];$('#employee').innerHTML='<option value="">Выберите сотрудника</option>'+list.map(x=>`<option value="${x.id}">${esc(x.full_name)}</option>`).join('')});
  $('#createAudit').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));try{const d=await api('/audits',{method:'POST',body:JSON.stringify(p)});openAudit(d.id)}catch(err){toast(err.message)}};
}
async function openAudit(id){try{if(!state.questions.length)state.questions=await api('/audits/questionnaire');state.audit=await api('/audits/'+id);if(state.audit.status==='completed')return renderResult(state.audit);state.visit=state.audit.current_visit||0;state.step=state.audit.current_step||0;renderWizard()}catch(e){toast(e.message)}}
function answersMap(){const m={};for(const a of state.audit.answers)m[`${a.visit_number}:${a.question_key}`]=a;return m}
function stepMeta(){if(state.step===0)return{title:'Общая информация',sub:'Заполняется один раз',screen:1};if(state.step===8)return{title:'Завершение дня',sub:'После пяти завершённых визитов',screen:37};return{title:['','Подготовка к визиту','Вступление','Осмотр','Презентация и работа с возражениями','Работа в точке и обучение персонала','Завершение визита','Анализ и комментарий'][state.step],sub:`Визит ${state.visit} из 5 · Шаг ${state.step} из 7`,screen:1+(state.visit-1)*7+state.step}}
function renderWizard(){
  const meta=stepMeta(),pct=Math.round(meta.screen/37*100),map=answersMap();
  let body='';
  if(state.step===0){
    body=questionCards(state.questions.filter(q=>q.step===0),0,map);
  }else if(state.step===8){
    body=questionCards(state.questions.filter(q=>q.step===8),0,map)+visitCheck();
  }else{
    const visit=state.audit.visits.find(v=>v.visit_number===state.visit);
    if(state.step===1){
      body=`<div class="card"><h2>Торговая точка</h2><div class="field"><label>Код торговой точки / код ТТ</label><input id="shopCode" value="${esc(visit?.shop_code||'')}" placeholder="Введите код ТТ"></div></div><div class="card"><h2>📍 Местоположение</h2><p class="muted">${visit?.latitude!=null?`Координаты сохранены, точность ${Math.round(visit.gps_accuracy||0)} м`:'Координаты сохраняются отдельно для этого визита.'}</p><button class="btn primary full" id="gps">Определить местоположение</button></div>`;
      body+=questionCards(state.questions.filter(q=>q.step===1),state.visit,map);
    }else{
      body=questionCards(state.questions.filter(q=>q.step===state.step),state.visit,map);
    }
    if(state.step===7){
      body+=`<div class="card"><h2>Комментарий</h2><div class="field"><label>Комментарий и рекомендации</label><textarea id="visitComment">${esc(visit?.comment||'')}</textarea></div></div>`;
    }
  }
  shell(`<div class="card"><strong>${esc(meta.title)}</strong><div class="muted">${esc(meta.sub)} · Экран ${meta.screen} из 37</div><div class="progress-wrap"><div class="progress" style="width:${pct}%"></div></div></div><div class="card accent"><h1>${esc(meta.title)}</h1><p class="muted">${esc(meta.sub)}</p></div>${body}<div class="save-state" id="saveState">Все изменения сохраняются автоматически</div><div class="bottom"><button class="btn secondary" id="prev">Назад</button><button class="btn primary" id="next">${state.step===8?'Отправить':'Далее'}</button></div>`);bindWizard()}
function questionCards(qs,visit,map){let out='',last='';for(const q of qs){if(q.section!==last){if(last)out+='</div>';out+=`<div class="card"><h2>${esc(q.section)}</h2><p class="muted">${q.allow_na?'Доступен ответ N/A':'Ответ N/A не используется'}</p>`;last=q.section}const a=map[`${visit}:${q.key}`];out+=`<div class="question" data-key="${q.key}" data-visit="${visit}"><div class="question-title">${esc(q.text)} *</div><div class="answers"><button class="answer ${a?.answer_value==='1'?'selected':''}" data-value="1">1 — выполнено</button><button class="answer ${a?.answer_value==='0'?'selected':''}" data-value="0">0 — не выполнено</button>${q.allow_na?`<button class="answer ${a?.answer_value==='N/A'?'selected':''}" data-value="N/A">N/A — не применимо</button>`:''}</div><div class="field comment" ${a&&['0','N/A'].includes(a.answer_value)?'':'hidden'}><label>Комментарий обязателен</label><textarea>${esc(a?.comment||'')}</textarea></div></div>`}if(last)out+='</div>';return out}
function visitCheck(){return`<div class="card"><h2>Проверка</h2>${state.audit.visits.map(v=>`<div class="visit-row"><span>Визит ${v.visit_number}: код ТТ ${esc(v.shop_code||'—')}</span><span>GPS ${v.gps_accuracy==null?'—':Math.round(v.gps_accuracy)+' м'}</span></div>`).join('')}</div>`}
function setSaving(t){const s=$('#saveState');if(s)s.textContent=t}
async function saveAnswer(card,value){const key=card.dataset.key,visit=Number(card.dataset.visit),comment=$('textarea',card)?.value?.trim()||null;if(['0','N/A'].includes(value)&&!comment){$('.comment',card).hidden=false;throw new Error('Для ответа 0 или N/A укажите комментарий')}setSaving('Сохранение…');await api(`/audits/${state.audit.id}/answer`,{method:'PUT',body:JSON.stringify({visit_number:visit,question_key:key,answer_value:value,comment})});const found=state.audit.answers.find(a=>a.visit_number===visit&&a.question_key===key);if(found){found.answer_value=value;found.comment=comment}else state.audit.answers.push({visit_number:visit,question_key:key,answer_value:value,comment});setSaving('Сохранено')}
function bindWizard(){$$('.answer').forEach(b=>b.onclick=async()=>{const card=b.closest('.question'),v=b.dataset.value;$('.comment',card).hidden=!['0','N/A'].includes(v);try{await saveAnswer(card,v);$$('.answer',card).forEach(x=>x.classList.toggle('selected',x===b))}catch(e){toast(e.message)}});$$('.comment textarea').forEach(t=>t.addEventListener('change',async()=>{const card=t.closest('.question'),sel=$('.answer.selected',card);if(sel)try{await saveAnswer(card,sel.dataset.value)}catch(e){toast(e.message)}}));$('#shopCode')?.addEventListener('change',saveVisitFields);$('#visitComment')?.addEventListener('change',saveVisitFields);$('#gps')?.addEventListener('click',()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(async p=>{await saveVisitFields({latitude:p.coords.latitude,longitude:p.coords.longitude,gps_accuracy:p.coords.accuracy});toast('Местоположение сохранено');state.audit=await api('/audits/'+state.audit.id);renderWizard()},e=>toast('Не удалось определить местоположение: '+e.message),{enableHighAccuracy:true,timeout:20000}):toast('Геолокация не поддерживается'));$('#prev').onclick=prevStep;$('#next').onclick=nextStep}
async function saveVisitFields(extra={}){if(!state.visit)return;const visit=state.audit.visits.find(v=>v.visit_number===state.visit),payload={};if($('#shopCode'))payload.shop_code=$('#shopCode').value.trim();if($('#visitComment'))payload.comment=$('#visitComment').value;Object.assign(payload,extra);await api(`/audits/${state.audit.id}/visits/${state.visit}`,{method:'PUT',body:JSON.stringify(payload)});Object.assign(visit,payload);setSaving('Сохранено')}
function currentComplete(){const map=answersMap(),qs=state.questions.filter(q=>q.step===state.step),visit=[0,8].includes(state.step)?0:state.visit;if(qs.some(q=>!map[`${visit}:${q.key}`]))return false;if(state.step===1){const v=state.audit.visits.find(x=>x.visit_number===state.visit);if(!v.shop_code||v.latitude==null)return false}return true}
async function saveProgress(){await api(`/audits/${state.audit.id}/progress`,{method:'PUT',body:JSON.stringify({current_visit:state.visit,current_step:state.step})})}
async function nextStep(){try{if(!currentComplete())throw new Error('Заполните все обязательные поля и ответы');if(state.step===8){const r=await api(`/audits/${state.audit.id}/submit`,{method:'POST'});state.audit={...state.audit,...r,status:'completed'};return renderResult(state.audit)}if(state.step===0){state.visit=1;state.step=1}else if(state.step<7)state.step++;else if(state.visit<5){state.visit++;state.step=1}else{state.visit=0;state.step=8}await saveProgress();renderWizard()}catch(e){toast(e.message)}}
async function prevStep(){if(state.step===0)return home();if(state.step===8){state.visit=5;state.step=7}else if(state.step>1)state.step--;else if(state.visit>1){state.visit--;state.step=7}else{state.visit=0;state.step=0}await saveProgress();renderWizard()}
function renderResult(a){shell(`<div class="card accent result"><div class="saved">✅ Результаты сохранены</div><div class="score">${Math.round(a.total_percent||0)}%</div><h1>${esc(a.level||'')}</h1><p class="muted">${esc(a.employee_name||'')}</p><button class="btn primary" id="toHome">На главную</button></div>`);$('#toHome').onclick=home}
async function adminPage(){
  let regions=[],users=[];
  try{[regions,users]=await Promise.all([api('/admin/regions'),api('/admin/users')])}catch(e){toast(e.message)}
  shell(`<div class="nav"><button class="pill" data-page="home">Главная</button><button class="pill active">Управление</button></div><div class="grid two">${state.me.role==='admin'?`<div class="card"><h2>Добавить регион</h2><form id="addRegion"><div class="field"><label>Название</label><input name="name" required></div><button class="btn primary" style="margin-top:12px">Добавить</button></form></div>`:''}<div class="card"><h2>Добавить сотрудника</h2><form id="addEmployee"><div class="field"><label>ФИО</label><input name="full_name" required></div><div class="field"><label>Регион</label><select name="region_id" required>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></div><div class="field"><label>Должность</label><input name="position"></div><button class="btn primary" style="margin-top:12px">Добавить</button></form></div></div><div class="card"><h2>Создать пользователя</h2><form id="addUser"><div class="grid two"><div class="field"><label>ФИО</label><input name="full_name" required></div><div class="field"><label>Логин</label><input name="login" minlength="3" required></div><div class="field"><label>Пароль</label><input name="password" type="password" minlength="8" placeholder="Минимум 8 символов" required></div><div class="field"><label>Роль</label><select name="role" id="userRole"><option value="leader">Руководитель</option><option value="manager">Менеджер (вся республика)</option>${state.me.role==='admin'?'<option value="admin">Администратор</option>':''}</select></div><div class="field" id="regionField" style="grid-column:1/-1"><label>Регион руководителя</label><select name="region_id" required>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select><small class="muted">Руководитель работает только в одном выбранном регионе.</small></div></div><button class="btn primary" style="margin-top:12px">Создать</button></form></div><div class="card"><h2>Пользователи</h2><div class="table-wrap"><table class="table"><tr><th>ФИО</th><th>Логин</th><th>Роль</th><th>Доступ</th></tr>${users.map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(u.login)}</td><td>${u.role==='manager'?'Менеджер':u.role==='leader'?'Руководитель':'Администратор'}</td><td>${u.role==='leader'?(u.regions.map(r=>esc(r.name)).join(', ')||'Регион не назначен'):'Вся республика'}</td></tr>`).join('')}</table></div></div>`);
  bindNav();
  const toggleRegion=()=>{const leader=$('#userRole').value==='leader';$('#regionField').hidden=!leader;$('#regionField select').required=leader};
  $('#userRole').onchange=toggleRegion;toggleRegion();
  $('#addRegion')&&($('#addRegion').onsubmit=async e=>{e.preventDefault();try{await api('/admin/regions?name='+encodeURIComponent(new FormData(e.target).get('name')),{method:'POST'});toast('Регион добавлен');adminPage()}catch(err){toast(err.message)}});
  $('#addEmployee').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));const q=new URLSearchParams(p);try{await api('/admin/employees?'+q,{method:'POST'});toast('Сотрудник добавлен');e.target.reset()}catch(err){toast(err.message)}};
  $('#addUser').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.region_ids=p.role==='leader'&&p.region_id?[p.region_id]:[];delete p.region_id;try{await api('/admin/users',{method:'POST',body:JSON.stringify(p)});toast('Пользователь создан');adminPage()}catch(err){toast(err.message)}};
}
boot();
