async function getEmployees(regionId){
  if(state.employees.has(regionId))return state.employees.get(regionId);
  const cached=JSON.parse(localStorage.getItem('sle_employees_'+regionId)||'null');if(cached){state.employees.set(regionId,cached);return cached}
  const list=await api('/audits/employees?region_id='+encodeURIComponent(regionId));state.employees.set(regionId,list);localStorage.setItem('sle_employees_'+regionId,JSON.stringify(list));return list;
}
async function newAuditForm(){
  let regions=state.regions||[];try{if(!regions.length){regions=await api('/audits/regions');state.regions=regions;localStorage.setItem('sle_regions',JSON.stringify(regions))}}catch(e){return toast(e.message)}
  const fixed=state.me.role==='leader';if(fixed&&regions.length!==1)return toast('Для руководителя должен быть назначен один регион');
  let employees=[];if(fixed)employees=await getEmployees(regions[0].id);
  const users=['admin','manager'].includes(state.me.role)?await api('/admin/users').catch(()=>[]):[];
  const leaders=users.filter(x=>x.role==='leader');
  const leaderField=state.me.role==='manager'?`<div class="field"><label>Руководитель</label><select name="leader_id" id="auditLeader" required><option value="">Выберите руководителя</option>${leaders.map(x=>`<option value="${x.id}" data-region="${x.regions?.[0]?.id||''}">${esc(x.full_name)}</option>`).join('')}</select></div>`:'';
  shell(`<div class="card accent"><h1>Новый аудит</h1><form id="createAudit"><div class="grid two"><div class="field"><label>Дата</label><input type="date" name="audit_date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Регион</label>${fixed?`<input value="${esc(regions[0].name)}" disabled><input type="hidden" name="region_id" value="${regions[0].id}">`:`<select name="region_id" id="region" required><option value="">Выберите регион</option>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select>`}</div>${leaderField}<div class="field ${state.me.role==='manager'?'':'span-2'}"><label>Сотрудник</label><select name="employee_id" id="employee" required><option value="">Выберите сотрудника</option>${employees.map(x=>`<option value="${x.id}" data-leader="${x.leader_id||''}">${esc(x.full_name)}</option>`).join('')}</select></div></div><div class="actions top-gap"><button type="button" class="btn secondary" id="back">Назад</button><button class="btn primary">Создать аудит</button></div></form></div>`);
  $('#back').onclick=home;
  async function refreshEmployees(){const region=$('#region')?.value||regions[0]?.id||'';const list=region?await getEmployees(region):[];const leader=$('#auditLeader')?.value||'';const filtered=leader?list.filter(x=>x.leader_id===leader):list;$('#employee').innerHTML='<option value="">Выберите сотрудника</option>'+filtered.map(x=>`<option value="${x.id}" data-leader="${x.leader_id||''}">${esc(x.full_name)}</option>`).join('')}
  $('#region')?.addEventListener('change',async e=>{if($('#auditLeader')){$$('#auditLeader option').forEach(o=>{if(o.value)o.hidden=!!e.target.value&&o.dataset.region!==e.target.value});$('#auditLeader').value=''}await refreshEmployees()});
  $('#auditLeader')?.addEventListener('change',refreshEmployees);
  $('#createAudit').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));try{const d=await api('/audits',{method:'POST',body:JSON.stringify(p)});openAudit(d.id)}catch(err){toast(err.message)}};
}
async function openAudit(id){try{if(!state.questions.length){state.questions=await api('/audits/questionnaire');localStorage.setItem('sle_questions',JSON.stringify(state.questions))}state.audit=await api('/audits/'+id);if(state.audit.status==='completed')return renderResult(state.audit);state.visit=state.audit.current_visit||0;state.step=state.audit.current_step||0;renderWizard()}catch(e){toast(e.message)}}
function answersMap(){const m={};for(const a of state.audit.answers)m[`${a.visit_number}:${a.question_key}`]=a;return m}
function stepMeta(){if(state.step===0)return{title:'Общая информация',sub:'Заполняется один раз',screen:1};if(state.step===8)return{title:'Завершение дня',sub:'После пяти завершённых визитов',screen:37};return{title:['','Подготовка к визиту','Вступление','Осмотр','Презентация и работа с возражениями','Работа в точке и обучение персонала','Завершение визита','Анализ и комментарий'][state.step],sub:`Визит ${state.visit} из 5 · Шаг ${state.step} из 7`,screen:1+(state.visit-1)*7+state.step}}
function renderWizard(){
  const meta=stepMeta(),pct=Math.round(meta.screen/37*100),map=answersMap();let body='';
  if(state.step===0)body=questionCards(state.questions.filter(q=>q.step===0),0,map);
  else if(state.step===8)body=questionCards(state.questions.filter(q=>q.step===8),0,map)+visitCheck();
  else{
    const visit=state.audit.visits.find(v=>v.visit_number===state.visit);
    if(state.step===1){body=`<div class="card"><h2>Торговая точка</h2><div class="field"><label>Код торговой точки / код ТТ</label><input id="shopCode" value="${esc(visit?.shop_code||'')}" placeholder="Введите код ТТ"></div></div><div class="card"><h2>📍 Местоположение</h2><p class="muted">${visit?.latitude!=null&&visit?.longitude!=null?`GPS сохранён: ${Number(visit.latitude).toFixed(6)}, ${Number(visit.longitude).toFixed(6)} · точность ${Math.round(visit.gps_accuracy||0)} м`:'Для каждого визита необходимо определить GPS-координаты торговой точки.'}</p><button type="button" class="btn primary full" id="gps">${visit?.latitude!=null?'Обновить местоположение':'Определить местоположение'}</button></div>`+questionCards(state.questions.filter(q=>q.step===1),state.visit,map)}
    else body=questionCards(state.questions.filter(q=>q.step===state.step),state.visit,map);
    if(state.step===7)body+=`<div class="card"><h2>Комментарий</h2><div class="field"><label>Комментарий и рекомендации</label><textarea id="visitComment">${esc(visit?.comment||'')}</textarea></div></div>`;
  }
  shell(`<div class="card"><strong>${esc(meta.title)}</strong><div class="muted">${esc(meta.sub)} · Экран ${meta.screen} из 37</div><div class="progress-wrap"><div class="progress" style="width:${pct}%"></div></div></div><div class="card accent"><h1>${esc(meta.title)}</h1><p class="muted">${esc(meta.sub)}</p></div>${body}<div class="save-state" id="saveState">Все изменения сохраняются автоматически</div><div class="bottom"><span class="actions"><button class="btn secondary" id="prev">Назад</button><button class="btn primary" id="next">${state.step===8?'Отправить':'Далее'}</button></span></div>`);bindWizard();
}
function questionCards(qs,visit,map){let out='',last='';for(const q of qs){if(q.section!==last){if(last)out+='</div>';out+=`<div class="card"><h2>${esc(q.section)}</h2>`;last=q.section}const a=map[`${visit}:${q.key}`];out+=`<div class="question" data-key="${q.key}" data-visit="${visit}"><div class="question-title">${esc(q.text)} *</div><div class="answers two-options"><button class="answer ${a?.answer_value==='1'?'selected':''}" data-value="1">1 — выполнено</button><button class="answer ${a?.answer_value==='0'?'selected':''}" data-value="0">0 — не выполнено</button></div></div>`}if(last)out+='</div>';return out}
function visitCheck(){return`<div class="card"><h2>Проверка</h2>${state.audit.visits.map(v=>`<div class="visit-row"><span>Визит ${v.visit_number}: ${esc(v.shop_code||'—')}</span><span>${v.latitude!=null&&v.longitude!=null?esc(v.latitude+', '+v.longitude):'Координаты не указаны'}</span></div>`).join('')}</div>`}
function setSaving(t){const s=$('#saveState');if(s)s.textContent=t}
function updateLocalAnswer(visit,key,value){let found=state.audit.answers.find(a=>a.visit_number===visit&&a.question_key===key);if(found){found.answer_value=value;found.comment=null}else{found={visit_number:visit,question_key:key,answer_value:value,comment:null};state.audit.answers.push(found)}state.pendingAnswers.set(`${visit}:${key}`,found);persistDraft();scheduleSync()}
function persistDraft(){if(state.audit)localStorage.setItem('sle_draft_'+state.audit.id,JSON.stringify({answers:state.audit.answers,visits:state.audit.visits,current_visit:state.visit,current_step:state.step,ts:Date.now()}))}
function scheduleSync(delay=700){setSaving('Сохранение…');clearTimeout(state.syncTimer);state.syncTimer=setTimeout(()=>flushSync().catch(e=>{setSaving('Ошибка сохранения');toast(e.message)}),delay)}
async function flushSync(extra={}){if(state.syncing)return state.syncing;clearTimeout(state.syncTimer);const answers=[...state.pendingAnswers.values()].map(a=>({visit_number:a.visit_number,question_key:a.question_key,answer_value:a.answer_value,comment:null}));const visitPayload=Object.keys(state.pendingVisit).length?{...state.pendingVisit}:null;if(!answers.length&&!visitPayload&&!Object.keys(extra).length){setSaving('Сохранено');return}const payload={answers,current_visit:state.visit,current_step:state.step,...extra};if(visitPayload&&state.visit){payload.visit_number=state.visit;payload.visit=visitPayload}state.syncing=api(`/audits/${state.audit.id}/sync`,{method:'PUT',body:JSON.stringify(payload)}).then(()=>{answers.forEach(a=>state.pendingAnswers.delete(`${a.visit_number}:${a.question_key}`));if(visitPayload)for(const k of Object.keys(visitPayload))delete state.pendingVisit[k];setSaving('Сохранено')}).finally(()=>state.syncing=null);return state.syncing}
function bindWizard(){if(state.visit&&state.step===1)api(`/extras/audit/${state.audit.id}/visit/${state.visit}/start`,{method:'POST'}).catch(()=>{});$$('.answer').forEach(b=>b.onclick=()=>{const card=b.closest('.question');updateLocalAnswer(Number(card.dataset.visit),card.dataset.key,b.dataset.value);$$('.answer',card).forEach(x=>x.classList.toggle('selected',x===b))});$('#shopCode')?.addEventListener('input',saveVisitFields);$('#gps')?.addEventListener('click',captureGps);$('#visitComment')?.addEventListener('input',saveVisitFields);$('#prev').onclick=prevStep;$('#next').onclick=nextStep}
function saveVisitFields(extra={}){if(!state.visit)return;const visit=state.audit.visits.find(v=>v.visit_number===state.visit),payload={};if($('#shopCode'))payload.shop_code=$('#shopCode').value.trim();if($('#visitComment'))payload.comment=$('#visitComment').value;Object.assign(payload,extra);Object.assign(visit,payload);Object.assign(state.pendingVisit,payload);persistDraft();scheduleSync()}
function captureGps(){if(!navigator.geolocation)return toast('Геолокация не поддерживается на этом устройстве');const btn=$('#gps');if(btn){btn.disabled=true;btn.textContent='Определение местоположения…'}navigator.geolocation.getCurrentPosition(async p=>{try{saveVisitFields({latitude:p.coords.latitude,longitude:p.coords.longitude,gps_accuracy:p.coords.accuracy});await flushSync();toast('GPS-координаты сохранены');renderWizard()}catch(e){toast(e.message)}},e=>{if(btn){btn.disabled=false;btn.textContent='Определить местоположение'};const messages={1:'Доступ к геолокации запрещён',2:'Местоположение недоступно',3:'Превышено время ожидания GPS'};toast(messages[e.code]||('Не удалось определить местоположение: '+e.message))},{enableHighAccuracy:true,timeout:25000,maximumAge:0})}
function currentComplete(){const map=answersMap(),qs=state.questions.filter(q=>q.step===state.step),visit=[0,8].includes(state.step)?0:state.visit;if(qs.some(q=>!map[`${visit}:${q.key}`]))return false;if(state.step===1){const v=state.audit.visits.find(x=>x.visit_number===state.visit);if(!v.shop_code||v.latitude==null||v.longitude==null)return false}return true}
async function saveProgress(){await flushSync({current_visit:state.visit,current_step:state.step})}
async function nextStep(){try{if(!currentComplete())throw new Error('Заполните код ТТ, определите GPS и ответьте на все вопросы');if(state.step===8){await flushSync();const r=await api(`/audits/${state.audit.id}/submit`,{method:'POST'});state.audit={...state.audit,...r,status:'completed'};return renderResult(state.audit)}if(state.step===0){state.visit=1;state.step=1}else if(state.step<7)state.step++;else if(state.visit<5){await api(`/extras/audit/${state.audit.id}/visit/${state.visit}/end`,{method:'POST'}).catch(()=>{});state.visit++;state.step=1}else{await api(`/extras/audit/${state.audit.id}/visit/${state.visit}/end`,{method:'POST'}).catch(()=>{});state.visit=0;state.step=8}await saveProgress();renderWizard()}catch(e){toast(e.message)}}
async function prevStep(){if(state.step===0)return home();if(state.step===8){state.visit=5;state.step=7}else if(state.step>1)state.step--;else if(state.visit>1){state.visit--;state.step=7}else{state.visit=0;state.step=0}await saveProgress();renderWizard()}
function renderResult(a){shell(`<div class="card accent result"><div class="saved">✅ Результаты сохранены</div><div class="score">${Math.round(a.total_percent||0)}%</div><h1>${esc(a.level||'')}</h1><p class="muted">${esc(a.employee_name||'')}</p><button class="btn primary" id="toHome">На главную</button></div>`);$('#toHome').onclick=home}
