async function history(){
  try{state.audits=await api('/audits?limit=500')}catch(e){return toast(e.message)}
  shell(`${mainNav('history')}<div class="card"><div class="section-head"><div><h1>Отчёты</h1><p class="muted">Все доступные аудиты</p></div><input id="reportSearch" class="search" placeholder="Поиск по сотруднику или региону"></div><div class="actions"><button class="btn primary" id="exportExcel">Отчет по аудиту</button><button class="btn secondary" id="exportAnswers">Детальный отчет</button></div><div id="reportTable" class="top-gap">${auditTable(state.audits)}</div></div>`);
  bindNav();$('#exportExcel').onclick=()=>downloadExcel('/extras/export/audit-report.xlsx','audit-report.xlsx');$('#exportAnswers').onclick=()=>downloadExcel('/extras/export/detailed-report.xlsx','detailed-audit-report.xlsx');$('#reportSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();const rows=state.audits.filter(a=>[a.employee_name,a.region_name,a.auditor_name,a.level].some(v=>String(v||'').toLowerCase().includes(q)));$('#reportTable').innerHTML=auditTable(rows);$$('[data-open]').forEach(r=>r.onclick=()=>openAudit(r.dataset.open))};
}
function statBar(label,value,count){return`<div class="stat-row"><div class="stat-label"><span>${esc(label)}</span><strong>${value}%</strong></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div><small>${count} ауд.</small></div>`}
async function dashboard(filters={}){
  const qs=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));
  let d;try{d=await api('/audits/dashboard'+(qs.toString()?'?'+qs.toString():''))}catch(e){return toast(e.message)}
  const f=d.filters||{regions:[],auditors:[],employees:[],months:[],selected:{}};
  const sel=f.selected||{};
  const maxLevel=Math.max(1,...Object.values(d.levels));
  const filterBox=`<div class="card dashboard-filters"><h2>Фильтры</h2><div class="grid four"><div class="field"><label>Регион</label><select id="dashRegion"><option value="">Все регионы</option>${f.regions.map(x=>`<option value="${x.id}" ${sel.region_id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Руководитель</label><select id="dashAuditor"><option value="">Все</option>${f.auditors.map(x=>`<option value="${x.id}" ${sel.auditor_id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Сотрудник</label><select id="dashEmployee"><option value="">Все сотрудники</option>${f.employees.map(x=>`<option value="${x.id}" data-region="${x.region_id}" ${sel.employee_id===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Месяц</label><select id="dashMonth"><option value="">Все месяцы</option>${f.months.map(x=>`<option value="${x}" ${sel.month===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="actions top-gap"><button class="btn primary" id="applyDashFilters">Применить</button><button class="btn secondary" id="resetDashFilters">Сбросить</button></div></div>`;
  shell(`${mainNav('dashboard')}<div class="dashboard-head"><div><h1>Дашборд</h1><p class="muted">Статистика по завершённым аудитам</p></div></div>${filterBox}<div class="kpi-grid dashboard-kpis">
    <div class="kpi kpi-audits"><div class="kpi-icon">✓</div><div class="kpi-copy"><span>Завершено аудитов</span><strong>${d.total}</strong><small>Всего за выбранный период</small></div></div>
    <div class="kpi kpi-average"><div class="kpi-icon">★</div><div class="kpi-copy"><span>Средний результат</span><strong>${d.average}%</strong><small>Средний показатель аудитов</small></div></div>
    <div class="kpi kpi-master"><div class="kpi-icon">🏆</div><div class="kpi-copy"><span>Мастер</span><strong>${d.levels['Мастер']||0}</strong><small>${d.total?Math.round((d.levels['Мастер']||0)/d.total*100):0}% от общего числа</small></div></div>
    <div class="kpi kpi-confident"><div class="kpi-icon">◆</div><div class="kpi-copy"><span>Уверенный</span><strong>${d.levels['Уверенный']||0}</strong><small>${d.total?Math.round((d.levels['Уверенный']||0)/d.total*100):0}% от общего числа</small></div></div>
    <div class="kpi kpi-basic"><div class="kpi-icon">●</div><div class="kpi-copy"><span>Базовый</span><strong>${d.levels['Базовый']||0}</strong><small>${d.total?Math.round((d.levels['Базовый']||0)/d.total*100):0}% от общего числа</small></div></div>
  </div><div class="card"><h2>Результаты по каждому блоку</h2>${d.blocks?.length?`<div class="table-wrap"><table class="table block-results"><thead><tr><th>Блок</th><th>Кол-во оценок</th><th>Средний результат</th></tr></thead><tbody>${d.blocks.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.count}</td><td><div class="block-result-cell"><strong>${x.average}%</strong><div class="mini-bar"><i style="width:${Math.max(0,Math.min(100,x.average))}%"></i></div></div></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Нет данных</p>'}</div><div class="grid two"><div class="card"><h2>Уровни оценки</h2>${Object.entries(d.levels).map(([name,count])=>`<div class="level-row"><span>${esc(name)}</span><div class="mini-bar"><i style="width:${count/maxLevel*100}%"></i></div><strong>${count}</strong></div>`).join('')}</div><div class="card"><h2>Динамика по месяцам</h2>${d.months.length?d.months.map(x=>statBar(x.month,x.average,x.count)).join(''):'<p class="muted">Нет данных</p>'}</div></div><div class="grid two"><div class="card"><h2>Результаты по регионам</h2>${d.regions.length?d.regions.map(x=>statBar(x.name,x.average,x.count)).join(''):'<p class="muted">Нет данных</p>'}</div><div class="card"><h2>Топ сотрудников</h2>${d.employees.length?`<div class="table-wrap"><table class="table"><tr><th>Сотрудник</th><th>Регион</th><th>Среднее</th><th>Аудиты</th></tr>${d.employees.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.region)}</td><td><strong>${x.average}%</strong></td><td>${x.count}</td></tr>`).join('')}</table></div>`:'<p class="muted">Нет данных</p>'}</div></div><div class="card"><h2>Последние завершённые аудиты</h2>${d.recent.length?`<div class="table-wrap"><table class="table"><tr><th>Дата</th><th>Визит</th><th>Код точки</th><th>Результат точки</th><th>Зона роста сотрудника</th><th>Локация точки</th></tr>${d.recent.map(x=>`<tr data-open="${x.id}" class="clickable"><td>${esc(x.audit_date)}</td><td>Точка ${x.visit_number}</td><td>${esc(x.shop_code||'—')}</td><td><strong>${x.total_percent??'—'}%</strong></td><td>${esc(x.growth_zone||'—')}</td><td>${x.location_url?`<a href="${x.location_url}" target="_blank" rel="noopener" onclick="event.stopPropagation()"><span class="location-pin">📍</span> Локация</a>`:'—'}</td></tr>`).join('')}</table></div>`:'<p class="muted">Нет данных</p>'}</div>`);
  bindNav();
  $('#applyDashFilters').onclick=()=>dashboard({region_id:$('#dashRegion').value,auditor_id:$('#dashAuditor').value,employee_id:$('#dashEmployee').value,month:$('#dashMonth').value});
  $('#resetDashFilters').onclick=()=>dashboard();
  $('#dashRegion').onchange=e=>{const region=e.target.value;$$('#dashEmployee option').forEach(o=>{if(!o.value)return;o.hidden=!!region&&o.dataset.region!==region});if($('#dashEmployee').selectedOptions[0]?.hidden)$('#dashEmployee').value=''};
}
